USE [master]
GO

/****** Object:  Database [MYIMBO]    Script Date: 5/3/2024 10:16:48 ******/
CREATE DATABASE [MYIMBO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MYIMBO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MYIMBO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MYIMBO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MYIMBO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MYIMBO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MYIMBO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MYIMBO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MYIMBO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MYIMBO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MYIMBO] SET ARITHABORT OFF 
GO

ALTER DATABASE [MYIMBO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MYIMBO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MYIMBO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MYIMBO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MYIMBO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MYIMBO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MYIMBO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MYIMBO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MYIMBO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MYIMBO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MYIMBO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MYIMBO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MYIMBO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MYIMBO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MYIMBO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MYIMBO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MYIMBO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MYIMBO] SET RECOVERY FULL 
GO

ALTER DATABASE [MYIMBO] SET  MULTI_USER 
GO

ALTER DATABASE [MYIMBO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MYIMBO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MYIMBO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MYIMBO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MYIMBO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MYIMBO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MYIMBO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MYIMBO] SET  READ_WRITE 
GO